
version: "3.1"
services:
  nodejs:
    image: jack892709/node-dev:node24-0.0.0
    working_dir: /application
    volumes:
      - ..:/application
    environment:
      - FE_DEV_PORT
      - FE_SSR_PORT
    ports:
      - "${FE_DEV_PORT}:${FE_DEV_PORT}"
      - "${FE_SSR_PORT}:${FE_SSR_PORT}"
    command: >
      bash -c 'for((i=1;;i+=2)); do sleep 1 && echo "Counter: $$i"; done'
    profiles:
      - web-services
